package com.cecj03.papago.model;

// Generated 2014/5/19 �U�� 03:55:39 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * MemStatusType generated by hbm2java
 */
public class MemStatusType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int memstatusId;
	private String memStatus;
	private Set papaMems = new HashSet(0);

	public MemStatusType() {
	}

	public MemStatusType(int memstatusId, String memStatus) {
		this.memstatusId = memstatusId;
		this.memStatus = memStatus;
	}

	public MemStatusType(int memstatusId, String memStatus, Set papaMems) {
		this.memstatusId = memstatusId;
		this.memStatus = memStatus;
		this.papaMems = papaMems;
	}

	public int getMemstatusId() {
		return this.memstatusId;
	}

	public void setMemstatusId(int memstatusId) {
		this.memstatusId = memstatusId;
	}

	public String getMemStatus() {
		return this.memStatus;
	}

	public void setMemStatus(String memStatus) {
		this.memStatus = memStatus;
	}

	public Set getPapaMems() {
		return this.papaMems;
	}

	public void setPapaMems(Set papaMems) {
		this.papaMems = papaMems;
	}

}
