package com.cecj03.papago.model;

// Generated 2014-5-21 15:30:38 by Hibernate Tools 3.4.0.CR1

/**
 * PapaScore generated by hbm2java
 */
public class PapaScore implements java.io.Serializable {

	private int scoreId;
	private PapaShop papaShop;
	private PapaMem papaMem;
	private int score;
	private java.sql.Timestamp scoreDate;

	public PapaScore() {
	}

	public PapaScore(int scoreId, PapaShop papaShop, PapaMem papaMem, int score, java.sql.Timestamp scoreDate) {
		this.scoreId = scoreId;
		this.papaShop = papaShop;
		this.papaMem = papaMem;
		this.score = score;
		this.scoreDate = scoreDate;
	}

	public int getScoreId() {
		return this.scoreId;
	}

	public void setScoreId(int scoreId) {
		this.scoreId = scoreId;
	}

	public PapaShop getPapaShop() {
		return this.papaShop;
	}

	public void setPapaShop(PapaShop papaShop) {
		this.papaShop = papaShop;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public int getScore() {
		return this.score;
	}

	public void setScore(int score) {
		this.score = score;
	}

	public java.sql.Timestamp getScoreDate() {
		return this.scoreDate;
	}

	public void setScoreDate(java.sql.Timestamp scoreDate) {
		this.scoreDate = scoreDate;
	}

}
