package com.cecj03.papago.model;

// Generated 2014/5/19 �U�� 03:55:39 by Hibernate Tools 4.0.0



/**
 * PapaRec generated by hbm2java
 */
public class PapaRec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int recId;
	private ShopType shopType;
	private PapaMem papaMem;
	private String name;
	private String phone;
	private String email;
	private String recAddress;
	private String contactName;
	private String contactPhone;
	private String price;
	private String web;
	private String note;

	public PapaRec() {
	}

	public PapaRec(int recId, ShopType shopType, PapaMem papaMem,
			String name, String phone, String recAddress,
			String price) {
		this.recId = recId;
		this.shopType = shopType;
		this.papaMem = papaMem;
		this.name = name;
		this.phone = phone;
		this.recAddress = recAddress;
		this.price = price;
	}

	public PapaRec(int recId, ShopType shopType, PapaMem papaMem,
			String name, String phone, String email,
			String recAddress, String contactName,
			String contactPhone, String price, String web,
			String note) {
		this.recId = recId;
		this.shopType = shopType;
		this.papaMem = papaMem;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.recAddress = recAddress;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.price = price;
		this.web = web;
		this.note = note;
	}

	public int getRecId() {
		return this.recId;
	}

	public void setRecId(int recId) {
		this.recId = recId;
	}

	public ShopType getShopType() {
		return this.shopType;
	}

	public void setShopType(ShopType shopType) {
		this.shopType = shopType;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getRecAddress() {
		return this.recAddress;
	}

	public void setRecAddress(String recAddress) {
		this.recAddress = recAddress;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
