package com.cecj03.papago.model;

// Generated 2014/5/19 �U�� 03:55:39 by Hibernate Tools 4.0.0



import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * PapaMem generated by hbm2java
 */
public class PapaMem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int memId;
	private MemType memType;
	private MemStatusType memStatusType;
	private String account;
	private String name;
	private String memPassword;
	private byte[] memPic;
	private String email;
	private String sex;
	private java.util.Date birth;
	private String phone;
	private String memAddress;
	private Timestamp memDate;
	private Set<?> updateShops = new HashSet(0);
	private Set<?> reportMsgs = new HashSet(0);
	private Set<?> papaScores = new HashSet(0);
	private Set<?> favoritesLists = new HashSet(0);
	private Set<?> papaRecs = new HashSet(0);
	private Set<?> papaMsgs = new HashSet(0);

	public PapaMem() {
	}

	public PapaMem(int memId, MemType memType, MemStatusType memStatusType,
			String account, String name, String memPassword,
			String email, String sex, java.util.Date birth,
			String phone, String memAddress, Timestamp memDate) {
		this.memId = memId;
		this.memType = memType;
		this.memStatusType = memStatusType;
		this.account = account;
		this.name = name;
		this.memPassword = memPassword;
		this.email = email;
		this.sex = sex;
		this.birth = birth;
		this.phone = phone;
		this.memAddress = memAddress;
		this.memDate = memDate;
	}

	public PapaMem(int memId, MemType memType, MemStatusType memStatusType,
			String account, String name, String memPassword,
			byte[] memPic, String email, String sex, java.util.Date birth,
			String phone, String memAddress, Timestamp memDate,
			Set<?> updateShops, Set<?> reportMsgs, Set<?> papaScores,
			Set<?> favoritesLists, Set<?> papaRecs, Set<?> papaMsgs) {
		this.memId = memId;
		this.memType = memType;
		this.memStatusType = memStatusType;
		this.account = account;
		this.name = name;
		this.memPassword = memPassword;
		this.memPic = memPic;
		this.email = email;
		this.sex = sex;
		this.birth = birth;
		this.phone = phone;
		this.memAddress = memAddress;
		this.memDate = memDate;
		this.updateShops = updateShops;
		this.reportMsgs = reportMsgs;
		this.papaScores = papaScores;
		this.favoritesLists = favoritesLists;
		this.papaRecs = papaRecs;
		this.papaMsgs = papaMsgs;
	}

	public int getMemId() {
		return this.memId;
	}

	public void setMemId(int memId) {
		this.memId = memId;
	}

	public MemType getMemType() {
		return this.memType;
	}

	public void setMemType(MemType memType) {
		this.memType = memType;
	}

	public MemStatusType getMemStatusType() {
		return this.memStatusType;
	}

	public void setMemStatusType(MemStatusType memStatusType) {
		this.memStatusType = memStatusType;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getMemPassword() {
		return this.memPassword;
	}

	public void setMemPassword(String memPassword) {
		this.memPassword = memPassword;
	}

	public byte[] getMemPic() {
		return this.memPic;
	}

	public void setMemPic(byte[] memPic) {
		this.memPic = memPic;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public java.util.Date getBirth() {
		return this.birth;
	}

	public void setBirth(java.util.Date birth) {
		this.birth = birth;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMemAddress() {
		return this.memAddress;
	}

	public void setMemAddress(String memAddress) {
		this.memAddress = memAddress;
	}

	public Timestamp getMemDate() {
		return this.memDate;
	}

	public void setMemDate(Timestamp memDate) {
		this.memDate = memDate;
	}

	public Set<?> getUpdateShops() {
		return this.updateShops;
	}

	public void setUpdateShops(Set<?> updateShops) {
		this.updateShops = updateShops;
	}

	public Set<?> getReportMsgs() {
		return this.reportMsgs;
	}

	public void setReportMsgs(Set<?> reportMsgs) {
		this.reportMsgs = reportMsgs;
	}

	public Set<?> getPapaScores() {
		return this.papaScores;
	}

	public void setPapaScores(Set<?> papaScores) {
		this.papaScores = papaScores;
	}

	public Set<?> getFavoritesLists() {
		return this.favoritesLists;
	}

	public void setFavoritesLists(Set<?> favoritesLists) {
		this.favoritesLists = favoritesLists;
	}

	public Set<?> getPapaRecs() {
		return this.papaRecs;
	}

	public void setPapaRecs(Set<?> papaRecs) {
		this.papaRecs = papaRecs;
	}

	public Set<?> getPapaMsgs() {
		return this.papaMsgs;
	}

	public void setPapaMsgs(Set<?> papaMsgs) {
		this.papaMsgs = papaMsgs;
	}

}
