package com.cecj03.papago.model;

import java.sql.Timestamp;

// Generated 2014/5/19 �U�� 03:55:39 by Hibernate Tools 4.0.0




/**
 * ReportMsg generated by hbm2java
 */
public class ReportMsg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int repId;
	private PapaMsg papaMsg;
	private PapaMem papaMem;
	private Timestamp reportDate;
	private String report;

	public ReportMsg() {
	}

	public ReportMsg(int repId, PapaMsg papaMsg, PapaMem papaMem,
			Timestamp reportDate, String report) {
		this.repId = repId;
		this.papaMsg = papaMsg;
		this.papaMem = papaMem;
		this.reportDate = reportDate;
		this.report = report;
	}

	public int getRepId() {
		return this.repId;
	}

	public void setRepId(int repId) {
		this.repId = repId;
	}

	public PapaMsg getPapaMsg() {
		return this.papaMsg;
	}

	public void setPapaMsg(PapaMsg papaMsg) {
		this.papaMsg = papaMsg;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public Timestamp getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Timestamp reportDate) {
		this.reportDate = reportDate;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

}
