package com.cecj03.papago.model;

import java.sql.Timestamp;

// Generated 2014/5/19 �U�� 03:55:39 by Hibernate Tools 4.0.0




/**
 * UpdateShop generated by hbm2java
 */
public class UpdateShop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int updateId;
	private PapaShop papaShop;
	private PapaMem papaMem;
	private Timestamp updateDate;
	private String updateContent;

	public UpdateShop() {
	}

	public UpdateShop(int updateId, PapaShop papaShop, PapaMem papaMem,
			Timestamp updateDate, String updateContent) {
		this.updateId = updateId;
		this.papaShop = papaShop;
		this.papaMem = papaMem;
		this.updateDate = updateDate;
		this.updateContent = updateContent;
	}

	public int getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(int updateId) {
		this.updateId = updateId;
	}

	public PapaShop getPapaShop() {
		return this.papaShop;
	}

	public void setPapaShop(PapaShop papaShop) {
		this.papaShop = papaShop;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

}
