package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

/**
 * FavoritesListId generated by hbm2java
 */
public class FavoritesListId implements java.io.Serializable {

	private int memId;
	private int shopId;

	public FavoritesListId() {
	}

	public FavoritesListId(int memId, int shopId) {
		this.memId = memId;
		this.shopId = shopId;
	}

	public int getMemId() {
		return this.memId;
	}

	public void setMemId(int memId) {
		this.memId = memId;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesListId))
			return false;
		FavoritesListId castOther = (FavoritesListId) other;

		return (this.getMemId() == castOther.getMemId())
				&& (this.getShopId() == castOther.getShopId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMemId();
		result = 37 * result + this.getShopId();
		return result;
	}

}
