package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MemStatusType generated by hbm2java
 */
public class MemStatusType implements java.io.Serializable {

	private int memstatusId;
	private String memStatus;
	private Set papaMems = new HashSet(0);

	public MemStatusType() {
	}

	public MemStatusType(int memstatusId, String memStatus) {
		this.memstatusId = memstatusId;
		this.memStatus = memStatus;
	}

	public MemStatusType(int memstatusId, String memStatus, Set papaMems) {
		this.memstatusId = memstatusId;
		this.memStatus = memStatus;
		this.papaMems = papaMems;
	}

	public int getMemstatusId() {
		return this.memstatusId;
	}

	public void setMemstatusId(int memstatusId) {
		this.memstatusId = memstatusId;
	}

	public String getMemStatus() {
		return this.memStatus;
	}

	public void setMemStatus(String memStatus) {
		this.memStatus = memStatus;
	}

	public Set getPapaMems() {
		return this.papaMems;
	}

	public void setPapaMems(Set papaMems) {
		this.papaMems = papaMems;
	}

}
