package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PapaShop generated by hbm2java
 */
public class PapaShop implements java.io.Serializable {

	private int shopId;
	private ShopStatusType shopStatusType;
	private PriceType priceType;
	private ShopType shopType;
	private String name;
	private String phone;
	private String email;
	private String shopPic;
	private String shopAddress;
	private Date shopDate;
	private String contactName;
	private String contactPhone;
	private String price;
	private String web;
	private String note;
	private Set papaScores = new HashSet(0);
	private Set papaMsgs = new HashSet(0);
	private Set updateShops = new HashSet(0);
	private Set favoritesLists = new HashSet(0);

	public PapaShop() {
	}

	public PapaShop(int shopId, ShopStatusType shopStatusType,
			PriceType priceType, ShopType shopType, String name,
			String phone, String shopAddress, Date shopDate,
			String price) {
		this.shopId = shopId;
		this.shopStatusType = shopStatusType;
		this.priceType = priceType;
		this.shopType = shopType;
		this.name = name;
		this.phone = phone;
		this.shopAddress = shopAddress;
		this.shopDate = shopDate;
		this.price = price;
	}

	public PapaShop(int shopId, ShopStatusType shopStatusType,
			PriceType priceType, ShopType shopType, String name,
			String phone, String email, String shopPic,
			String shopAddress, Date shopDate, String contactName,
			String contactPhone, String price, String web,
			String note, Set papaScores, Set papaMsgs, Set updateShops,
			Set favoritesLists) {
		this.shopId = shopId;
		this.shopStatusType = shopStatusType;
		this.priceType = priceType;
		this.shopType = shopType;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.shopPic = shopPic;
		this.shopAddress = shopAddress;
		this.shopDate = shopDate;
		this.contactName = contactName;
		this.contactPhone = contactPhone;
		this.price = price;
		this.web = web;
		this.note = note;
		this.papaScores = papaScores;
		this.papaMsgs = papaMsgs;
		this.updateShops = updateShops;
		this.favoritesLists = favoritesLists;
	}

	public int getShopId() {
		return this.shopId;
	}

	public void setShopId(int shopId) {
		this.shopId = shopId;
	}

	public ShopStatusType getShopStatusType() {
		return this.shopStatusType;
	}

	public void setShopStatusType(ShopStatusType shopStatusType) {
		this.shopStatusType = shopStatusType;
	}

	public PriceType getPriceType() {
		return this.priceType;
	}

	public void setPriceType(PriceType priceType) {
		this.priceType = priceType;
	}

	public ShopType getShopType() {
		return this.shopType;
	}

	public void setShopType(ShopType shopType) {
		this.shopType = shopType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getShopPic() {
		return this.shopPic;
	}

	public void setShopPic(String shopPic) {
		this.shopPic = shopPic;
	}

	public String getShopAddress() {
		return this.shopAddress;
	}

	public void setShopAddress(String shopAddress) {
		this.shopAddress = shopAddress;
	}

	public Date getShopDate() {
		return this.shopDate;
	}

	public void setShopDate(Date shopDate) {
		this.shopDate = shopDate;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactPhone() {
		return this.contactPhone;
	}

	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set getPapaScores() {
		return this.papaScores;
	}

	public void setPapaScores(Set papaScores) {
		this.papaScores = papaScores;
	}

	public Set getPapaMsgs() {
		return this.papaMsgs;
	}

	public void setPapaMsgs(Set papaMsgs) {
		this.papaMsgs = papaMsgs;
	}

	public Set getUpdateShops() {
		return this.updateShops;
	}

	public void setUpdateShops(Set updateShops) {
		this.updateShops = updateShops;
	}

	public Set getFavoritesLists() {
		return this.favoritesLists;
	}

	public void setFavoritesLists(Set favoritesLists) {
		this.favoritesLists = favoritesLists;
	}

}
