package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * PriceType generated by hbm2java
 */
public class PriceType implements java.io.Serializable {

	private int pricetypeId;
	private String priceType;
	private Set papaShops = new HashSet(0);

	public PriceType() {
	}

	public PriceType(int pricetypeId, String priceType) {
		this.pricetypeId = pricetypeId;
		this.priceType = priceType;
	}

	public PriceType(int pricetypeId, String priceType, Set papaShops) {
		this.pricetypeId = pricetypeId;
		this.priceType = priceType;
		this.papaShops = papaShops;
	}
	
	public static int convertInt(String data) {
		int result = 0;
		try {
			result = Integer.parseInt(data);
		} catch (NumberFormatException e) {
			e.printStackTrace();
			result = -1000;
		}
		return result;
	}

	public int getPricetypeId() {
		return this.pricetypeId;
	}

	public void setPricetypeId(int pricetypeId) {
		this.pricetypeId = pricetypeId;
	}

	public String getPriceType() {
		return this.priceType;
	}

	public void setPriceType(String priceType) {
		this.priceType = priceType;
	}

	public Set getPapaShops() {
		return this.papaShops;
	}

	public void setPapaShops(Set papaShops) {
		this.papaShops = papaShops;
	}

}
