package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ReportMsg generated by hbm2java
 */
public class ReportMsg implements java.io.Serializable {

	private int repId;
	private PapaMsg papaMsg;
	private PapaMem papaMem;
	private Date reportDate;
	private String report;

	public ReportMsg() {
	}

	public ReportMsg(int repId, PapaMsg papaMsg, PapaMem papaMem,
			Date reportDate, String report) {
		this.repId = repId;
		this.papaMsg = papaMsg;
		this.papaMem = papaMem;
		this.reportDate = reportDate;
		this.report = report;
	}

	public int getRepId() {
		return this.repId;
	}

	public void setRepId(int repId) {
		this.repId = repId;
	}

	public PapaMsg getPapaMsg() {
		return this.papaMsg;
	}

	public void setPapaMsg(PapaMsg papaMsg) {
		this.papaMsg = papaMsg;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public Date getReportDate() {
		return this.reportDate;
	}

	public void setReportDate(Date reportDate) {
		this.reportDate = reportDate;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

}
