package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ShopStatusType generated by hbm2java
 */
public class ShopStatusType implements java.io.Serializable {

	private int shopstatusId;
	private String shopStatus;
	private Set papaShops = new HashSet(0);

	public ShopStatusType() {
	}

	public ShopStatusType(int shopstatusId, String shopStatus) {
		this.shopstatusId = shopstatusId;
		this.shopStatus = shopStatus;
	}

	public ShopStatusType(int shopstatusId, String shopStatus,
			Set papaShops) {
		this.shopstatusId = shopstatusId;
		this.shopStatus = shopStatus;
		this.papaShops = papaShops;
	}

	public int getShopstatusId() {
		return this.shopstatusId;
	}

	public void setShopstatusId(int shopstatusId) {
		this.shopstatusId = shopstatusId;
	}

	public String getShopStatus() {
		return this.shopStatus;
	}

	public void setShopStatus(String shopStatus) {
		this.shopStatus = shopStatus;
	}

	public Set getPapaShops() {
		return this.papaShops;
	}

	public void setPapaShops(Set papaShops) {
		this.papaShops = papaShops;
	}

}
