package com.cecj03.papago.model.entity;

// Generated 2014-5-20 15:38:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UpdateShop generated by hbm2java
 */
public class UpdateShop implements java.io.Serializable {

	private int updateId;
	private PapaShop papaShop;
	private PapaMem papaMem;
	private Date updateDate;
	private String updateContent;

	public UpdateShop() {
	}

	public UpdateShop(int updateId, PapaShop papaShop, PapaMem papaMem,
			Date updateDate, String updateContent) {
		this.updateId = updateId;
		this.papaShop = papaShop;
		this.papaMem = papaMem;
		this.updateDate = updateDate;
		this.updateContent = updateContent;
	}

	public int getUpdateId() {
		return this.updateId;
	}

	public void setUpdateId(int updateId) {
		this.updateId = updateId;
	}

	public PapaShop getPapaShop() {
		return this.papaShop;
	}

	public void setPapaShop(PapaShop papaShop) {
		this.papaShop = papaShop;
	}

	public PapaMem getPapaMem() {
		return this.papaMem;
	}

	public void setPapaMem(PapaMem papaMem) {
		this.papaMem = papaMem;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getUpdateContent() {
		return this.updateContent;
	}

	public void setUpdateContent(String updateContent) {
		this.updateContent = updateContent;
	}

}
